### PR TITLE
bau: Epdq is deprecated

### PR DESCRIPTION
**Pull request by oswaldquek**
Not only is epdq deprecated, these tests were never turned into canaries.

### CODE REVIEW

**Comment by katstevens** [comment]
You'll need to remove the lines from [webpack.config.js](https://github.com/alphagov/pay-smoke-tests/blob/76cda466df15b0fcbee17ee193dc8c123be37614/webpack.config.js) (and the commented-out bit of `run-local/index.js`) (oh and the epdq section of the README!).

**Comment by katstevens** [comment]
I think we can remove the EPDQ section of the README now too?

**Comment by oswaldquek** [comment]
> I think we can remove the EPDQ section of the README now too?

Whoops, removed

**Review by katstevens — APPROVED** [review]
🔥

**Pull request merged**
